# Generated by Django 4.2.11 on 2024-03-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='challenge name')),
                ('description', models.TextField(verbose_name='challenge description')),
                ('enter_price', models.IntegerField(default=0, verbose_name='challenge enter price')),
                ('reward_price', models.IntegerField(default=0, verbose_name='challenge reward price')),
                ('attended_number', models.IntegerField(default=0, verbose_name='challenge attended number')),
                ('mission_count', models.IntegerField(default=0, verbose_name='challenge mission count')),
                ('difficulty', models.IntegerField(choices=[(1, 'آسان'), (2, 'متوسط'), (3, 'سخت')], default=0, verbose_name='challenge difficulty')),
                ('start_time', models.DateTimeField(verbose_name='challenge start time')),
                ('end_time', models.DateTimeField(verbose_name='challenge end time')),
                ('status', models.BooleanField(default=True, verbose_name='challenge status')),
                ('challenge_type', models.IntegerField(choices=[(1, 'معمایی'), (2, 'چالشی'), (3, 'ترکیبی')], default=1, verbose_name='mission type')),
            ],
            options={
                'verbose_name': 'مسابقه',
                'verbose_name_plural': 'مسابقات',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='mission name')),
                ('description', models.TextField(verbose_name='mission description')),
                ('mission_type', models.IntegerField(choices=[(1, 'معمایی'), (2, 'چالشی')], default=1, verbose_name='mission type')),
                ('correct_answers', models.JSONField(blank=True, default=list, null=True, verbose_name='mission correct answers')),
                ('mission_order', models.IntegerField(default=0, verbose_name='mission order')),
                ('challenge', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge', verbose_name='mission challenge id')),
            ],
            options={
                'verbose_name': 'مرحله',
                'verbose_name_plural': 'مراحل',
            },
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='user mission user id')),
                ('status', models.BooleanField(default=True, verbose_name='user mission status')),
                ('video_id', models.IntegerField(blank=True, null=True, verbose_name='user mission video_id')),
                ('image_id', models.IntegerField(blank=True, null=True, verbose_name='user mission image_id')),
                ('answer', models.CharField(blank=True, max_length=50, null=True, verbose_name='user mission answer')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='user mission time')),
                ('like_video', models.IntegerField(default=0, verbose_name='user mission like video')),
                ('acceptance', models.BooleanField(default=True, verbose_name='user mission acceptance')),
                ('challenge', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge', verbose_name='user_mission_challenge')),
                ('mission_id', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='challenge.mission', verbose_name='user_mission_mission_id')),
            ],
            options={
                'verbose_name': 'مرحله ی کاریر',
                'verbose_name_plural': 'مراحل کاربر',
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='userChallenge user id')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='user challenge register_time')),
                ('challenge', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge', verbose_name='userchallenge_challenge')),
                ('current_mission', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.mission', verbose_name='userchallenge_mission')),
            ],
            options={
                'verbose_name': 'مسابقه کاریر',
                'verbose_name_plural': 'مسابقات کاربر',
            },
        ),
    ]
