# Generated by Django 4.2.11 on 2024-03-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='correct_answers',
            field=models.TextField(blank=True, null=True, verbose_name='mission correct answers'),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='current_mission',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.mission', verbose_name='userchallenge_current_mission'),
        ),
        migrations.AlterField(
            model_name='usermission',
            name='acceptance',
            field=models.IntegerField(choices=[(1, 'تایید نشده'), (2, 'در انتظار تایید'), (3, 'تایید شده')], default=1, verbose_name='user mission acceptance'),
        ),
        migrations.AlterField(
            model_name='usermission',
            name='answer',
            field=models.CharField(blank=True, default=0, max_length=50, null=True, verbose_name='user mission answer'),
        ),
        migrations.AlterField(
            model_name='usermission',
            name='image_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='user mission image_id'),
        ),
        migrations.AlterField(
            model_name='usermission',
            name='video_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='user mission video_id'),
        ),
    ]
