# Generated by Django 4.2.11 on 2024-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_mission_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user id')),
                ('level', models.IntegerField(default=1, verbose_name='user level')),
                ('xp', models.IntegerField(default=0, verbose_name='user xp')),
                ('max_xp', models.IntegerField(default=100, verbose_name='level max xp')),
            ],
        ),
        migrations.AlterField(
            model_name='mission',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'آسان'), (2, 'متوسط'), (3, 'سخت')], default=0, verbose_name='mission difficulty'),
        ),
        migrations.AlterField(
            model_name='usermission',
            name='answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='user mission answer'),
        ),
    ]
