# Generated by Django 4.2.11 on 2024-03-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_level_alter_mission_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermission',
            name='answer',
            field=models.JSONField(blank=True, max_length=500, null=True, verbose_name='user mission answer'),
        ),
    ]
