# Generated by Django 4.2.11 on 2024-03-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_alter_usermission_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='correct_answers',
            field=models.JSONField(blank=True, null=True, verbose_name='mission correct answers'),
        ),
    ]
