# Generated by Django 4.2.11 on 2024-03-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_alter_mission_correct_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
